### ISSUE TITLE
Migrate List of Giraf releases (starting from 2018)

### ISSUE THREAD

**Issue by MathiasLybech** [aau-giraf/wiki#10]
From http://web.giraf.cs.aau.dk/w/ the appropriate page should be found. Make sure to:

- [ ] Check for dead/wrong links (to phabricator or Gitlab, etc.) and correct them
- [ ] Check for obvious errors in the text - such as text references to the "phabricator wiki"
- [ ] Made sure it is formatted as [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

When the text has been corrected it should be committed to a separate branch, and a pull request should be created.

**Comment by swuf** [comment]
Taget af gruppe 8.

**Comment by Lrss** [comment]
Er tanken at dette bliver et Repository med Markdown filer, eller skal vi bruge Github Wiki systemet? @MathiasLybech

**Comment by Lrss** [comment]
Skal det gøres sådan her:
https://github.com/swuf/wiki/wiki
Eller:
https://github.com/swuf/wiki

**Comment by TobiasPalludan** [comment]
@Lrss det skal gerne være et repository. Så laver vi det til GitHub pages.
