### ISSUE TITLE
Document what the web-api-dotnetcore-build repository is responsible for and how it interact with other repositories

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/wiki#114]
Definition of done:
It should have enough information about the repository that a new student can open this document and gain a clear understanding about why the repository exsist and whats its used for.

**Comment by pegede17** [comment]
Så vidt vi kan se er dette repository depricated og benyttes ikke længere. Dog kan vi have overset noget. Der skal vendes tilbage efter det er helt klart hvordan vi laver en ny release.

**Comment by Lortemanden** [comment]
Eventuelt tage kontakt til nogle af de gammle elever og spørg dem omkring brugen. Hvis de ikke ved hvad det bruges til prøv at tage fat i procces gruppen og få dem til at arkivere det.

**Comment by Lortemanden** [comment]
Gruppe 16 har arbejdet med dette tidligere
