### ISSUE TITLE
Structure wiki so there is a link to all the wiki files

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/wiki#123]
Not all the files and information can be found when using the links from the wiki readme. 

**Describe the solution you'd like**
Making a dropdown list so that every file can be accessed from the wiki readme. The links should be structured with a dropdown menu as shown in the example. 
![Wiki](https://user-images.githubusercontent.com/55434783/75343064-ec8a1600-5897-11ea-8063-84da9ff1194d.PNG)

Most of the files in the wiki is not reachable from the links in the wiki readme. It is therefor also a part of the issue to structure the menu so its easy to navigate to each of the wiki files.

**Comment by mathiasandresen** [comment]
Is dependent on #133 
If the folders and files are renamed, the links will get lost.
It would therefor not be good to do this issue before #133 is done

**Comment by Lortemanden** [comment]
This issue might be fixed by issue #4
