### ISSUE TITLE
Document databases and tables

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/wiki#124]
Should include

- Which applications use which databases, i.e.
![image](https://user-images.githubusercontent.com/36476478/75350577-0c750600-58a7-11ea-84fa-224d0f6e8389.png)

- The tables in the databases, e.g. using diagrams (maybe ER) of all tables and attributes.
![image](https://user-images.githubusercontent.com/36476478/75350741-4ba35700-58a7-11ea-9e8d-cfedecc508cc.png)

**Comment by jkrod** [comment]
**NB! Related to** issue #200
