### ISSUE TITLE
Document API endpoints

### ISSUE THREAD

**Issue by Badgie** [aau-giraf/wiki#125]
All the endpoints available in the API and what they do. This could possibly just be a link to the swagger page that already documents it. It can be accessed at http://localhost:5000/swagger/index.html when hosting the API locally.

It can also be accessed on [production](http://srv.giraf.cs.aau.dk/DEV/API/swagger/index.html), however the relevant JSON file is missing, which produces an error.

**Comment by Lortemanden** [comment]
The task is to either document the API endpoints in the wiki OR put the relevant JSON file on the production and link to it in the wiki via following link https://srv.giraf.cs.aau.dk/DEV/API/swagger/index.html.

**Comment by soenderby** [comment]
This issue involves fully documenting the API endpoints in the wiki, as the swagger documentation is only available when the server is running.  
The documentation for the endpoints should include: 
 - The name and URL of the endpoint
 - A short description of the endpoint
 - How a request should be structured
 - How possible responses are structured
