### ISSUE TITLE
Document the move from Azure Pipelines to Github Actions

### ISSUE THREAD

**Issue by mathiasandresen** [aau-giraf/wiki#138]
* All pages in the wiki containing information about the Azure Pipeline should be revisitied.
* The Github Actions yaml file should be explained [/.github/workflows/main.yml](https://github.com/aau-giraf/weekplanner/blob/develop/.github/workflows/main.yml)

**Comment by Lortemanden** [comment]
Should the files containing Azure Pipeline be deleted, moved or edited?

**Comment by Lortemanden** [comment]
Group 10 has worked with this in sprint 1.
They have looked at it, but they have not started to write it.
Group 10 would like to continue working with it.

**Comment by Lortemanden** [comment]
Group 10 has worked with this in sprint 2. 
Has not made more then in sprint 1. 
Group 10 would like to work with this in sprint 3.

**Comment by mathiasandresen** [comment]
We have documented the GitHub Actions workflows at https://aau-giraf.github.io/wiki/development/continuous_integration/github_actions/
