### ISSUE TITLE
Enforce LTS

### ISSUE THREAD

**Issue by Jakobzs** [aau-giraf/wiki#140]
**Is your feature request related to a problem? Please describe.**
LTS (long-term support) should be enforced to minimize upgrading of software for future students.

**Describe the solution you'd like**
I think it is best to enforce LTS versions of software when it comes to GIRAF (such as Flutter, MySQL, .NET Core etc), as that means future students will spend less time worrying about having to upgrade parts and potentially break existing functionality. If no "LTS" exists, then a "stable" build should be enforced (such as with Flutter).

**Describe alternatives you've considered**

**Additional context**
This issue was primarily written because the students from 2019 decided to use .NET Core 2.2 for the Web-API which was already EOL (End-of-life) the same year (December 23, 2019 to be specific). If they had chosen .NET Core 2.1 on the other hand, it would be supported until August 21, 2021.

**Comment by Lortemanden** [comment]
I thought LTS only was relevant for the customers that was going to use the app, since it would still be the developers that would have to update the versions?

**Comment by Jakobzs** [comment]
It would definitely benefit both the customers and the developers. This issue is more thought of as a "guideline" that should be followed by the developers. For example, it would be unreasonable to pick Java 14 for development when it will expire in a few months, whereas Java 8 and Java 11 are LTS and therefore will last for many years.

So, my proposal is that developers should ONLY pick a LTS version when it comes to software. However if a LTS version does not exist, then a "stable" version (such as with Flutter) should be picked, as development/alpha/beta builds are likely to be error prone.

**Comment by Lortemanden** [comment]
This issue has been fixed by having the different versions in one file and recommending the next semester to keep updating the versions as it is needed.
