### ISSUE TITLE
As a developer i would like a short video about using/setting up the docker swarm so that other developers can easily get an overview

### ISSUE THREAD

**Issue by holyfailer** [aau-giraf/wiki#145]
**Describe the solution you'd like**
A short video that would help with knowledge sharing across groups about the docker swarm. The video should be put up on the wiki with either a direct video or a link to a youtube video.

**Describe alternatives you've considered**
no

**Comment by MarcusEggeStudent** [comment]
link til video ligger i bunden af "server_administration/ServerOverview.md"
