### ISSUE TITLE
The design guide is missing a fallback image

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/wiki#149]
**Is your feature request related to a problem? Please describe.**
There is no fallback image in the design guide which the developers need to implement a fallback image. 
**Describe the solution you'd like**
Update the design guide with a fallback image

**Describe alternatives you've considered**
None

**Comment by mathiasandresen** [comment]
Im not sure what is meant by this? A fallback image for the wiki? Or a fallback image in the applications?
