### ISSUE TITLE
Have a subdomain created for the GIRAF wiki

### ISSUE THREAD

**Issue by mathiasandresen** [aau-giraf/wiki#151]
**Describe the solution you'd like**
It would be nice to have a subdomain, e.g. `wiki.giraf.cs.aau.dk` or something like that.
I think we can have the subdomain setup by contacting ITS.
This page
https://help.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site
Contains information about how to setup a custom domain name on GH Pages.

**Describe alternatives you've considered**
Just using the standard https://aau-giraf.github.io/wiki/ provided by GitHub.

**Comment by Lortemanden** [comment]
Have this not already been solved by having the domain provided by GitHub?

**Comment by Kaliahh** [comment]
Solved by having github.io
