### ISSUE TITLE
Move readme from web-api to wiki

### ISSUE THREAD

**Issue by mads-bo** [aau-giraf/wiki#165]
**Is your feature request related to a problem? Please describe.**
The readme of the web-api repo describes how to setup the web-api on a local machine. This would make more sense to have on the wiki under a fitting category.

**Describe the solution you'd like**
The reame of web-api should contain a small description of the repo and a link to the wiki.

**Describe alternatives you've considered**
Do nothing. It's not very important, as the readme works.

**Additional context**
Link to the wiki: https://aau-giraf.github.io/wiki/

**Comment by T-Dawq** [comment]
Same as #190.

**Comment by zaztz** [comment]
This issues has been solve see https://aau-giraf.github.io/wiki/development/rest_api_development/BuildAndRunLocally/
