### ISSUE TITLE
Update wiki to reflect update to MySQL 8.0

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/wiki#189]
**Is your feature request related to a problem? Please describe.**
The change to MySQL in issue https://github.com/aau-giraf/giraf-production-swarm/issues/10 and PR https://github.com/aau-giraf/giraf-production-swarm/pull/11 is not reflected in the wiki

**Describe the solution you'd like**
Update the following pages to reflect the update to MySQL 8.0:
https://aau-giraf.github.io/wiki/development/server_administration/docker_swarm/Database/
![image](https://user-images.githubusercontent.com/17495079/80593568-c01e8180-8a21-11ea-8399-09ec0b60da4d.png)

https://aau-giraf.github.io/wiki/development/server_administration/docker_swarm/DockerSwarm/
![image](https://user-images.githubusercontent.com/17495079/80593616-d4627e80-8a21-11ea-9977-ff01c37810b6.png)

Check other places to make sure nothing was missed

**Describe alternatives you've considered**

**Additional context**

**Comment by jkrod** [comment]
**Update to this issue!!!**

The update should only be on the docker swarm relevant part, that is stuff such as the update to the .yaml file as the screenshots above show. Other updates about fx new attributes or tables in the database are done in the related issue #200 .

**Also**
I strongly encourage the removal of all history related stuff, such as how the update to MySql 5.x was made etc. This is not relevant and can quickly become confusing and overwhelming as time passes. What is relevant is how it is now and how you do certain relevant stuff, not how a specific previous update was performed.
