### ISSUE TITLE
As a developer I want a guide for how the local database can be implemented so that the next semester of students has a basis for solving weekplanner#389

### ISSUE THREAD

**Issue by Lortemanden** [aau-giraf/wiki#199]
**Is your feature request related to a problem? Please describe.**
We have tried to implement a local database, but a bad method was used and we had to restart. Instead of using another bad method we should find a good method

**Describe the solution you'd like**
A page in the wiki which describes a general guide to implement a local database so that next semesters students have a starting point. The guide should contain reflections on how to solve aau-giraf/weekplanner#389 with descriptions (and sources) of possible methods.

**Additional context**
The method should be used to implement aau-giraf/weekplanner#389 and the resulting wiki page should be linked from weekplanner#389.

**Comment by T-Dawq** [comment]
Group 8 and PO talked about this issue on 07.05.2020: The guide should not be a step by step guide to how to implement the database with detailed descriptions of relations. It should serve as a source of inspiration for the next semester of students with an overall description of different methods and reflections on how these methods would work in relation to GIRAF.
