### ISSUE TITLE
Missing steps for running the wiki locally

### ISSUE THREAD

**Issue by Laexander** [aau-giraf/wiki#210]
**Is your feature request related to a problem? Please describe.**
In the file [writing_wiki.md](https://github.com/aau-giraf/wiki/blob/feature_188/docs/writing_wiki.md) the guide for running the wiki locally does not mention that git needs to be installed and be placed in systemvariable PATH.

**Describe the solution you'd like**
The guide should include the steps required to install git

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/17495079/81303318-d52b8e00-907b-11ea-9cf5-a0effc9650a0.png)

**Comment by Kaliahh** [comment]
Deprecated
