### ISSUE TITLE
REST API Development TOC is not up to date

### ISSUE THREAD

**Issue by giano574** [aau-giraf/wiki#211]
Self-explanatory
![image](https://user-images.githubusercontent.com/17013720/81385242-4d915e00-9113-11ea-9427-9e52ebec7177.png)

Link #267

**Comment by soenderby** [comment]
An alternative solution is removing the Content section entirely, as an overview of all the pages is already available in the menu on the left-hand side.

**Comment by Kaliahh** [comment]
Related to #267
