### ISSUE TITLE
Some of the text should be formatted as inline code on Build and run the web-api locally

### ISSUE THREAD

**Issue by mathiasandresen** [aau-giraf/wiki#225]
**Is your feature request related to a problem? Please describe.**
As an example "http://10.0.2.2:5000" should be formatted as `http://10.0.2.2:5000` as seen in the image:
![billede](https://user-images.githubusercontent.com/5781825/82185850-293f3980-98ea-11ea-9a46-7261d4fb5bc1.png)

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by mathiasandresen** [comment]
Related to #190

**Comment by jkrod** [comment]
**NB! Et par ekstra ting**

Under 0. Prerequisites mangler der info om, hvordan man laver install af dotnet-ef:

> dotnet tool install --global dotnet-ef

Dette gøres når man i CMD står i GirafRest folder i ens lokale web-api repository

Og så er der en lille typo: Repo hedder web-api ikke web_api

![Udklip](https://user-images.githubusercontent.com/34282060/82190015-a7064380-98f0-11ea-91f1-b4db80404c02.JPG)
