### ISSUE TITLE
Sub-items aren't displayed properly on GitHub Pages

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/wiki#236]
**Is your feature request related to a problem? Please describe.**
Related to #163 . In the markdown, the sub-items for step 3 are shown properly with squares as bullets: https://github.com/aau-giraf/wiki/blob/master/docs/writing_wiki.md
In GitHub pages they are apparently not treated as sub-items: https://aau-giraf.github.io/wiki/writing_wiki/

**Describe the solution you'd like**
The sub-items under step 3 should be displayed properly on GitHub Pages as they are in the markdown.

**Additional context**
Screenshot from markdown:
![image](https://user-images.githubusercontent.com/55434874/82191888-7a076000-98f3-11ea-8966-4b6223bad29d.png)
Screenshot from GitHub Pages:
![image](https://user-images.githubusercontent.com/55434874/82192046-b8048400-98f3-11ea-9215-3a01db5eeb2b.png)

**Comment by gitkshn** [comment]
Der er nogle stavefejl, som jeg tænker at I kan løse samtidigt. 

> You should now be able to access the wiki at http://127.0.0.1:8000/. Step 1 to 3 only has to be done the first time, unless new plugins have been added (if so do **steop 3** again).
til:
> You should now be able to access the wiki at http://127.0.0.1:8000/. Step 1 to 3 only has to be done the first time, unless new plugins have been added (if so do step 4 again).
