### ISSUE TITLE
Transitions in JWT diagram has wrong numbers

### ISSUE THREAD

**Issue by rasmus91** [aau-giraf/wiki#247]
According to the original diagram, the JWT is obtained before the information is obtained from the database. The lefthand 2 and 3 should be switched

![jwt_api](https://user-images.githubusercontent.com/2297739/82483607-f1e2af80-9ad8-11ea-9886-9af40ee4ead2.png)

**Comment by soenderby** [comment]
Wiki page in question https://aau-giraf.github.io/wiki/development/rest_api_development/TokenAuthentication/
