### ISSUE TITLE
As an administrative project member I would like an overview of which wiki pages and folders should be updated each sprint and each semester

### ISSUE THREAD

**Issue by T-Dawq** [aau-giraf/wiki#249]
**Is your feature request related to a problem? Please describe.**
Wiki pages and folders such as https://github.com/aau-giraf/wiki/blob/master/docs/releases/index.md and https://github.com/aau-giraf/wiki/tree/master/docs/releases has to be updated each sprint.
https://github.com/aau-giraf/wiki/tree/master/docs/development/design_guide/prototypes has to updated each semester. 

**Describe the solution you'd like**
A wikipages containing links to pages and folders with descriptions of how and when they should be updated.

**Comment by soenderby** [comment]
The following pages should also be updated each semester:  
[Process Manual](https://github.com/aau-giraf/wiki/tree/master/docs/process_manual)  
[Advice for future GIRAF](https://github.com/aau-giraf/wiki/tree/master/docs/getting_started/advice_for_future_giraf)

**Comment by soenderby** [comment]
Closed by #278
