### ISSUE TITLE
The Giraf Github Wiki cannot be updated

### ISSUE THREAD

**Issue by JakobTopholt** [aau-giraf/wiki#295]
Currently the Giraf GitHub wiki cannot be updated. This is presumed to be due to the following https://github.com/aau-giraf/wiki/actions/runs/3590762558/jobs/6044505795 .

**Potential solution:**
Looking at the errors in the link above it would seem that some version of something might need to be updated. Good luck.

**Comment by andreaslborg** [comment]
https://aau-giraf.github.io/wiki/Development/Wiki/running_wiki/
