### ISSUE TITLE
Migrate the MySQL Database to Docker and document the work.

### ISSUE THREAD

**Issue by thomaslhansen** [aau-giraf/wiki#35]
**Is your feature request related to a problem? Please describe.**
In the current server setup the MySQL database server is a Docker Container which is running on an server that is going to be deleted. 

**Describe the solution you'd like**
I would like the MySQL server to be migrated into the Docker Stack that the new server can serve to its users and remember to document the work in the wiki.

**Describe alternatives you've considered**
Change database engine - Might be and option ask PO or Process group regarding this.

**Additional context**
Write a docker-compose file that can be used by a Docker Stack

**Comment by Tekrus** [comment]
If the server group decides that the change of database is appropriate, please write a section for the wiki, detailing why this choice was made.
