### ISSUE TITLE
Document how to access the different parts of the server infrastructure for future semesters.

### ISSUE THREAD

**Issue by thomaslhansen** [aau-giraf/wiki#36]
**Is your feature request related to a problem? Please describe.**
Is is a huge problem and pain to find all existing servers, how they are setup and the different tools used to mange them.

**Describe the solution you'd like**
Give a short concise and overview and make a guide on who to access the servers, how to take ownership and how to pass it on to future semesters. 

**Describe alternatives you've considered**
None 

**Additional context**
None

**Comment by Tekrus** [comment]
This should definitely be done before the end of the semester, but as long as the current server group has the information available, it is not essential to write it right now. (Priority will increase as time passes)
