### ISSUE TITLE
Use SSL

### ISSUE THREAD

**Issue by boginw** [aau-giraf/wiki#40]
**Is your feature request related to a problem? Please describe.**
As of now, our servers will only respond with `HTTP` requests. It is highly recommended to switch to `HTTPS` and redirect all traffic from `HTTP` over to `https` as `HTTP` is considered insecure. 

**Describe the solution you'd like**
We should move to `HTTPS`

**Describe alternatives you've considered**
None

**Comment by Lortemanden** [comment]
The issues should be moved to the repository where the changes have to be made. We have no idea where it is though. 

The http requests from the server should be changed to https request before this issue is solved.

**Comment by Lortemanden** [comment]
Group 16 had this in 2020 1. sprint

**Comment by joandrsn** [comment]
For the person assigned this issue:
If you do not know anything about TLS/SSL, please read that first.
Look into Let's Encrypt. Generally these: https://letsencrypt.org/docs/challenge-types/
As far as I can see in the `/share-nfs/nginx/` there is already a `.well-known`-folder. It might seem as if someone already has tried to set it up.

If you're setting Lets Encrypt up, please remember that the certificates expires on 90 days and you should setup a cronjob to create a new certificate.

For changing it on flutter URL, it could be as simple as adding a `s` here:
https://github.com/aau-giraf/weekplanner/blob/604f6f8973821f65a07a51efd5dec309788f3585/assets/environments.prod.json#L2
