### ISSUE TITLE
Migrate pages under Server Administration pages

### ISSUE THREAD

**Issue by MathiasLybech** [aau-giraf/wiki#5]
From http://web.giraf.cs.aau.dk/w/ the appropriate page should be found. Make sure to:

- [x] Check for dead/wrong links (to phabricator or Gitlab, etc.) and correct them
- [x] Check for obvious errors in the text - such as text references to the "phabricator wiki"
- [x] Made sure it is formatted as [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

When the text has been corrected it should be committed to a separate branch, and a pull request should be created.

**Comment by thomaslhansen** [comment]
Is this issue ready to be closed since it was merged in PR #12 ?

**Comment by llundbo** [comment]
Yes
