### ISSUE TITLE
Migrate pages under Xamarin Development(Week Planner) and Android Development

### ISSUE THREAD

**Issue by MathiasLybech** [aau-giraf/wiki#7]
From http://web.giraf.cs.aau.dk/w/ the appropriate page should be found. Make sure to:

- [x] Check for dead/wrong links (to phabricator or Gitlab, etc.) and correct them
- [x] Check for obvious errors in the text - such as text references to the "phabricator wiki"
- [x] Made sure it is formatted as [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

When the text has been corrected it should be committed to a separate branch, and a pull request should be created.

**Comment by thomaslhansen** [comment]
Er dette stadigt relevant for projektet efter vi har planlagt at skifte til Flutter? @aau-giraf/sw602f19

**Comment by thomaslhansen** [comment]
Er dette stadigt relevant for projektet efter vi har valgt at skifte til Flutter eller skal jeg bare migrere det over og markere det som depricated? @aau-giraf/sw610f19

**Comment by thomaslhansen** [comment]
@TobiasPalludan Since you dismissed my pull request with the argument that it is no longer relevant I will hereby close this issue.
